/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    materias: Materia;
    edicoes: Edicao;
    vinhos: Vinho;
    guias: Guia;
    eventos: Evento;
    autores: Autor;
    categorias: Categoria;
    tags: Tag;
    uvas: Uva;
    regioes: Regiao;
    importadoras: Importadora;
    midia: Midia;
    inscricoes: Inscricao;
    usuarios: Usuario;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    materias: MateriasSelect<false> | MateriasSelect<true>;
    edicoes: EdicoesSelect<false> | EdicoesSelect<true>;
    vinhos: VinhosSelect<false> | VinhosSelect<true>;
    guias: GuiasSelect<false> | GuiasSelect<true>;
    eventos: EventosSelect<false> | EventosSelect<true>;
    autores: AutoresSelect<false> | AutoresSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    uvas: UvasSelect<false> | UvasSelect<true>;
    regioes: RegioesSelect<false> | RegioesSelect<true>;
    importadoras: ImportadorasSelect<false> | ImportadorasSelect<true>;
    midia: MidiaSelect<false> | MidiaSelect<true>;
    inscricoes: InscricoesSelect<false> | InscricoesSelect<true>;
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    configuracoes: Configuracoes;
  };
  globalsSelect: {
    configuracoes: ConfiguracoesSelect<false> | ConfiguracoesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * O jornalismo do portal: reportagens, ensaios, entrevistas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materias".
 */
export interface Materia {
  id: number;
  titulo: string;
  /**
   * A linha fina, logo abaixo do título.
   */
  subtitulo?: string | null;
  /**
   * De 40 a 60 palavras, escritas para fazer sentido sozinhas, fora da página. É o trecho que buscadores e IAs vão citar.
   */
  resumo: string;
  destaque?: {
    imagem?: (number | null) | Midia;
    /**
     * Fotógrafo, ilustrador ou origem. Aparece embaixo da imagem.
     */
    credito?: string | null;
    legenda?: string | null;
  };
  corpo: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Viram cartões no fim da matéria e ligam a ficha ao texto.
   */
  vinhosRelacionados?: (number | Vinho)[] | null;
  materiasRelacionadas?: (number | Materia)[] | null;
  guiasRelacionados?: (number | Guia)[] | null;
  /**
   * Cada par vira um bloco no fim da página e entra no código que o Google e as IAs leem. Responda de forma auto-contida, sem depender do resto do texto.
   */
  faq?:
    | {
        pergunta: string;
        resposta: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Se ficar em branco, usamos o título, o resumo e a imagem de destaque da própria página.
   */
  seo?: {
    /**
     * Até 70 caracteres. Aparece na aba do navegador e no resultado do Google.
     */
    titulo?: string | null;
    /**
     * Até 165 caracteres. É o parágrafo cinza embaixo do link no Google.
     */
    descricao?: string | null;
    /**
     * A imagem que aparece quando o link é colado no WhatsApp, Instagram ou X.
     */
    imagem?: (number | null) | Midia;
    /**
     * Separe por vírgula. Não vai para a meta keywords (que morreu) — serve de guia editorial e alimenta a busca interna.
     */
    palavrasChave?: string | null;
    /**
     * Use com muita parcimônia. O portal inteiro depende de ser encontrado.
     */
    naoIndexar?: boolean | null;
    /**
     * Só preencha se este conteúdo foi publicado antes em outro lugar e aquele endereço deve continuar sendo o oficial.
     */
    canonica?: string | null;
  };
  /**
   * Preenchido sozinho a partir do título. Prefira slugs curtos, em português, com um tema só.
   */
  slug?: string | null;
  indiceBusca?: string | null;
  autor: number | Autor;
  categoria: number | Categoria;
  tags?: (number | Tag)[] | null;
  /**
   * A faixa da escala cromática do vinho que representa este conteúdo. É o que dá cor ao cartão, à fita do boletim e aos filtros.
   */
  chipCor?:
    | (
        | 'verde-palha'
        | 'palha'
        | 'ouro'
        | 'ouro-velho'
        | 'ambar'
        | 'laranja'
        | 'rosa-palido'
        | 'salmao'
        | 'cobre'
        | 'cereja'
        | 'rubi'
        | 'purpura'
        | 'granada'
        | 'tawny'
      )
    | null;
  /**
   * Deixe uma data futura para agendar. O conteúdo só aparece no site depois dela.
   */
  dataPublicacao?: string | null;
  /**
   * Aparece nas páginas evergreen. Atualize quando revisar o conteúdo.
   */
  dataAtualizacao?: string | null;
  /**
   * A home usa a matéria marcada mais recente como manchete.
   */
  destaqueHome?: boolean | null;
  /**
   * Calculado sozinho a partir do corpo.
   */
  tempoLeitura?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Imagens e ilustrações usadas no site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "midia".
 */
export interface Midia {
  id: number;
  /**
   * Descreva a imagem para quem não pode vê-la. É lido por leitores de tela e pelos buscadores.
   */
  alt: string;
  /**
   * Fotógrafo, ilustrador ou banco de imagem.
   */
  credito?: string | null;
  /**
   * Usada quando a matéria não define uma legenda própria.
   */
  legenda?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    miniatura?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cartao?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    quadrado?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    retrato?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    largura?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    compartilhamento?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * As fichas. Cada uma é uma página que responde uma pergunta inteira sobre uma garrafa.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vinhos".
 */
export interface Vinho {
  id: number;
  nome: string;
  produtor: string;
  pais: string;
  regiao?: (number | null) | Regiao;
  subRegiao?: string | null;
  /**
   * Deixe vazio para vinhos sem safra.
   */
  safra?: number | null;
  tipo: 'tinto' | 'branco' | 'rose' | 'espumante' | 'laranja' | 'fortificado';
  corpo?: ('leve' | 'medio' | 'encorpado') | null;
  teorAlcoolico?: number | null;
  /**
   * A cor real da taça. É o chip que a ficha carrega e o que liga a garrafa à escala cromática do portal.
   */
  corNaEscala:
    | 'verde-palha'
    | 'palha'
    | 'ouro'
    | 'ouro-velho'
    | 'ambar'
    | 'laranja'
    | 'rosa-palido'
    | 'salmao'
    | 'cobre'
    | 'cereja'
    | 'rubi'
    | 'purpura'
    | 'granada'
    | 'tawny';
  /**
   * Deixe o percentual vazio quando o produtor não informa.
   */
  uvas?:
    | {
        uva: number | Uva;
        percentual?: number | null;
        id?: string | null;
      }[]
    | null;
  destaque?: {
    imagem?: (number | null) | Midia;
    /**
     * Fotógrafo, ilustrador ou origem. Aparece embaixo da imagem.
     */
    credito?: string | null;
    legenda?: string | null;
  };
  /**
   * Meias taças são permitidas: 3,5 · 4 · 4,5 · 5.
   */
  nota?: number | null;
  /**
   * Duas ou três frases que se sustentam sozinhas, fora da página. É o trecho que buscadores e IAs vão citar quando alguém perguntar sobre este vinho.
   */
  veredito: string;
  notasDegustacao?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  harmonizacoes?:
    | {
        prato: string;
        observacao?: string | null;
        id?: string | null;
      }[]
    | null;
  temperaturaServico?: string | null;
  potencialGuarda?: string | null;
  tacaRecomendada?: string | null;
  decantacao?: string | null;
  faixaPreco?: ('ate-80' | '80-150' | '150-250' | '250-400' | '400-700' | 'acima-700') | null;
  /**
   * Aparece na ficha, para o leitor saber o quanto a faixa está fresca.
   */
  dataPreco?: string | null;
  importadora?: (number | null) | Importadora;
  /**
   * Links informativos, sem afiliação. Se algum dia houver afiliação, marque abaixo — a transparência é parte da credibilidade.
   */
  ondeComprar?:
    | {
        loja: string;
        url: string;
        afiliado?: boolean | null;
        id?: string | null;
      }[]
    | null;
  materiasRelacionadas?: (number | Materia)[] | null;
  vinhosSimilares?: (number | Vinho)[] | null;
  guiasRelacionados?: (number | Guia)[] | null;
  /**
   * Cada par vira um bloco no fim da página e entra no código que o Google e as IAs leem. Responda de forma auto-contida, sem depender do resto do texto.
   */
  faq?:
    | {
        pergunta: string;
        resposta: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Se ficar em branco, usamos o título, o resumo e a imagem de destaque da própria página.
   */
  seo?: {
    /**
     * Até 70 caracteres. Aparece na aba do navegador e no resultado do Google.
     */
    titulo?: string | null;
    /**
     * Até 165 caracteres. É o parágrafo cinza embaixo do link no Google.
     */
    descricao?: string | null;
    /**
     * A imagem que aparece quando o link é colado no WhatsApp, Instagram ou X.
     */
    imagem?: (number | null) | Midia;
    /**
     * Separe por vírgula. Não vai para a meta keywords (que morreu) — serve de guia editorial e alimenta a busca interna.
     */
    palavrasChave?: string | null;
    /**
     * Use com muita parcimônia. O portal inteiro depende de ser encontrado.
     */
    naoIndexar?: boolean | null;
    /**
     * Só preencha se este conteúdo foi publicado antes em outro lugar e aquele endereço deve continuar sendo o oficial.
     */
    canonica?: string | null;
  };
  /**
   * Preenchido sozinho a partir do título. Prefira slugs curtos, em português, com um tema só.
   */
  slug?: string | null;
  indiceBusca?: string | null;
  autor: number | Autor;
  tags?: (number | Tag)[] | null;
  /**
   * Deixe uma data futura para agendar. O conteúdo só aparece no site depois dela.
   */
  dataPublicacao?: string | null;
  /**
   * Aparece nas páginas evergreen. Atualize quando revisar o conteúdo.
   */
  dataAtualizacao?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Regiões e denominações. Cada uma vira um filtro e pode ter um guia próprio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regioes".
 */
export interface Regiao {
  id: number;
  nome: string;
  /**
   * Preenchido sozinho a partir do título. Prefira slugs curtos, em português, com um tema só.
   */
  slug?: string | null;
  pais: string;
  descricao?: string | null;
  guia?: (number | null) | Guia;
  updatedAt: string;
  createdAt: string;
}
/**
 * Conteúdo que não vence. É o que sustenta o tráfego de busca e o que as IAs citam como referência.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guias".
 */
export interface Guia {
  id: number;
  titulo: string;
  subtitulo?: string | null;
  /**
   * De 40 a 60 palavras, escritas para fazer sentido sozinhas, fora da página. É o trecho que buscadores e IAs vão citar.
   */
  resumo: string;
  destaque?: {
    imagem?: (number | null) | Midia;
    /**
     * Fotógrafo, ilustrador ou origem. Aparece embaixo da imagem.
     */
    credito?: string | null;
    legenda?: string | null;
  };
  corpo: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Três a cinco frases curtas e auto-contidas. Abrem o guia e são o pedaço mais citável da página.
   */
  paraLevar?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  conteudosRelacionados?:
    | (
        | {
            relationTo: 'materias';
            value: number | Materia;
          }
        | {
            relationTo: 'guias';
            value: number | Guia;
          }
        | {
            relationTo: 'vinhos';
            value: number | Vinho;
          }
      )[]
    | null;
  vinhosExemplo?: (number | Vinho)[] | null;
  /**
   * Cada par vira um bloco no fim da página e entra no código que o Google e as IAs leem. Responda de forma auto-contida, sem depender do resto do texto.
   */
  faq?:
    | {
        pergunta: string;
        resposta: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Se ficar em branco, usamos o título, o resumo e a imagem de destaque da própria página.
   */
  seo?: {
    /**
     * Até 70 caracteres. Aparece na aba do navegador e no resultado do Google.
     */
    titulo?: string | null;
    /**
     * Até 165 caracteres. É o parágrafo cinza embaixo do link no Google.
     */
    descricao?: string | null;
    /**
     * A imagem que aparece quando o link é colado no WhatsApp, Instagram ou X.
     */
    imagem?: (number | null) | Midia;
    /**
     * Separe por vírgula. Não vai para a meta keywords (que morreu) — serve de guia editorial e alimenta a busca interna.
     */
    palavrasChave?: string | null;
    /**
     * Use com muita parcimônia. O portal inteiro depende de ser encontrado.
     */
    naoIndexar?: boolean | null;
    /**
     * Só preencha se este conteúdo foi publicado antes em outro lugar e aquele endereço deve continuar sendo o oficial.
     */
    canonica?: string | null;
  };
  /**
   * Preenchido sozinho a partir do título. Prefira slugs curtos, em português, com um tema só.
   */
  slug?: string | null;
  indiceBusca?: string | null;
  tipoGuia: 'uva' | 'regiao' | 'harmonizacao' | 'servico' | 'compra' | 'tecnico';
  nivel: 'iniciante' | 'intermediario';
  autor: number | Autor;
  tags?: (number | Tag)[] | null;
  /**
   * A faixa da escala cromática do vinho que representa este conteúdo. É o que dá cor ao cartão, à fita do boletim e aos filtros.
   */
  chipCor?:
    | (
        | 'verde-palha'
        | 'palha'
        | 'ouro'
        | 'ouro-velho'
        | 'ambar'
        | 'laranja'
        | 'rosa-palido'
        | 'salmao'
        | 'cobre'
        | 'cereja'
        | 'rubi'
        | 'purpura'
        | 'granada'
        | 'tawny'
      )
    | null;
  /**
   * Deixe uma data futura para agendar. O conteúdo só aparece no site depois dela.
   */
  dataPublicacao?: string | null;
  /**
   * Aparece nas páginas evergreen. Atualize quando revisar o conteúdo.
   */
  dataAtualizacao?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Quem assina o conteúdo. A ficha alimenta a página /sobre e o schema Person.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autores".
 */
export interface Autor {
  id: number;
  nome: string;
  /**
   * Preenchido sozinho a partir do título. Prefira slugs curtos, em português, com um tema só.
   */
  slug?: string | null;
  /**
   * Ex.: "Jornalista de vinho e criadora da Tanin".
   */
  cargo?: string | null;
  /**
   * Uma ou duas frases. Aparece no pé das matérias.
   */
  bioCurta?: string | null;
  /**
   * Texto completo da página /sobre.
   */
  bioLonga?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  foto?: (number | null) | Midia;
  /**
   * Formação, certificações, prêmios e veículos onde publicou. É o que sustenta a autoridade do portal aos olhos do Google e das IAs.
   */
  credenciais?:
    | {
        texto: string;
        ano?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Entram no `sameAs` do schema — é assim que buscadores ligam a pessoa aos perfis dela.
   */
  redes?:
    | {
        rede: 'instagram' | 'linkedin' | 'youtube' | 'x' | 'tiktok' | 'site' | 'outro';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Aparece na página /sobre se preenchido.
   */
  email?: string | null;
  /**
   * Opcional. Se ficar em branco, usamos o título, o resumo e a imagem de destaque da própria página.
   */
  seo?: {
    /**
     * Até 70 caracteres. Aparece na aba do navegador e no resultado do Google.
     */
    titulo?: string | null;
    /**
     * Até 165 caracteres. É o parágrafo cinza embaixo do link no Google.
     */
    descricao?: string | null;
    /**
     * A imagem que aparece quando o link é colado no WhatsApp, Instagram ou X.
     */
    imagem?: (number | null) | Midia;
    /**
     * Separe por vírgula. Não vai para a meta keywords (que morreu) — serve de guia editorial e alimenta a busca interna.
     */
    palavrasChave?: string | null;
    /**
     * Use com muita parcimônia. O portal inteiro depende de ser encontrado.
     */
    naoIndexar?: boolean | null;
    /**
     * Só preencha se este conteúdo foi publicado antes em outro lugar e aquele endereço deve continuar sendo o oficial.
     */
    canonica?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Assuntos livres. Servem para relacionar conteúdo, não para navegar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  nome: string;
  /**
   * Preenchido sozinho a partir do título. Prefira slugs curtos, em português, com um tema só.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * O vocabulário de castas. Cada uva vira um filtro no índice de vinhos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uvas".
 */
export interface Uva {
  id: number;
  nome: string;
  /**
   * Preenchido sozinho a partir do título. Prefira slugs curtos, em português, com um tema só.
   */
  slug?: string | null;
  cor?: ('tinta' | 'branca') | null;
  /**
   * Separados por vírgula. Ex.: Syrah, Shiraz.
   */
  sinonimos?: string | null;
  descricao?: string | null;
  /**
   * Se existir um guia dedicado, ligue aqui — vira link nas fichas.
   */
  guia?: (number | null) | Guia;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quem traz o vinho para o Brasil. Aparece na ficha e ajuda o leitor a encontrar a garrafa.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "importadoras".
 */
export interface Importadora {
  id: number;
  nome: string;
  /**
   * Preenchido sozinho a partir do título. Prefira slugs curtos, em português, com um tema só.
   */
  slug?: string | null;
  site?: string | null;
  cidade?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * As editorias do portal. Poucas e estáveis — categoria demais é o mesmo que nenhuma.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  nome: string;
  /**
   * Preenchido sozinho a partir do título. Prefira slugs curtos, em português, com um tema só.
   */
  slug?: string | null;
  descricao?: string | null;
  /**
   * A faixa da escala cromática do vinho que representa este conteúdo. É o que dá cor ao cartão, à fita do boletim e aos filtros.
   */
  chipCor?:
    | (
        | 'verde-palha'
        | 'palha'
        | 'ouro'
        | 'ouro-velho'
        | 'ambar'
        | 'laranja'
        | 'rosa-palido'
        | 'salmao'
        | 'cobre'
        | 'cereja'
        | 'rubi'
        | 'purpura'
        | 'granada'
        | 'tawny'
      )
    | null;
  ordem?: number | null;
  /**
   * Opcional. Se ficar em branco, usamos o título, o resumo e a imagem de destaque da própria página.
   */
  seo?: {
    /**
     * Até 70 caracteres. Aparece na aba do navegador e no resultado do Google.
     */
    titulo?: string | null;
    /**
     * Até 165 caracteres. É o parágrafo cinza embaixo do link no Google.
     */
    descricao?: string | null;
    /**
     * A imagem que aparece quando o link é colado no WhatsApp, Instagram ou X.
     */
    imagem?: (number | null) | Midia;
    /**
     * Separe por vírgula. Não vai para a meta keywords (que morreu) — serve de guia editorial e alimenta a busca interna.
     */
    palavrasChave?: string | null;
    /**
     * Use com muita parcimônia. O portal inteiro depende de ser encontrado.
     */
    naoIndexar?: boolean | null;
    /**
     * Só preencha se este conteúdo foi publicado antes em outro lugar e aquele endereço deve continuar sendo o oficial.
     */
    canonica?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * O arquivo do Boletim. Cada edição vira uma página própria e uma faixa na fita cromática.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "edicoes".
 */
export interface Edicao {
  id: number;
  titulo: string;
  subtitulo?: string | null;
  /**
   * De 40 a 60 palavras, escritas para fazer sentido sozinhas, fora da página. É o trecho que buscadores e IAs vão citar.
   */
  resumo: string;
  destaque?: {
    imagem?: (number | null) | Midia;
    /**
     * Fotógrafo, ilustrador ou origem. Aparece embaixo da imagem.
     */
    credito?: string | null;
    legenda?: string | null;
  };
  corpo: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  blocos?:
    | {
        titulo: string;
        /**
         * Preenchida sozinha a partir do título. É o que vem depois do # no endereço.
         */
        ancora?: string | null;
        resumo?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Se ficar em branco, usamos o título, o resumo e a imagem de destaque da própria página.
   */
  seo?: {
    /**
     * Até 70 caracteres. Aparece na aba do navegador e no resultado do Google.
     */
    titulo?: string | null;
    /**
     * Até 165 caracteres. É o parágrafo cinza embaixo do link no Google.
     */
    descricao?: string | null;
    /**
     * A imagem que aparece quando o link é colado no WhatsApp, Instagram ou X.
     */
    imagem?: (number | null) | Midia;
    /**
     * Separe por vírgula. Não vai para a meta keywords (que morreu) — serve de guia editorial e alimenta a busca interna.
     */
    palavrasChave?: string | null;
    /**
     * Use com muita parcimônia. O portal inteiro depende de ser encontrado.
     */
    naoIndexar?: boolean | null;
    /**
     * Só preencha se este conteúdo foi publicado antes em outro lugar e aquele endereço deve continuar sendo o oficial.
     */
    canonica?: string | null;
  };
  /**
   * Vira o número gigante da página, à maneira de revista.
   */
  numero: number;
  /**
   * Preenchido sozinho a partir do título. Prefira slugs curtos, em português, com um tema só.
   */
  slug?: string | null;
  indiceBusca?: string | null;
  dataEnvio: string;
  dataPublicacao?: string | null;
  /**
   * A faixa da escala cromática do vinho que representa este conteúdo. É o que dá cor ao cartão, à fita do boletim e aos filtros.
   */
  chipCor?:
    | (
        | 'verde-palha'
        | 'palha'
        | 'ouro'
        | 'ouro-velho'
        | 'ambar'
        | 'laranja'
        | 'rosa-palido'
        | 'salmao'
        | 'cobre'
        | 'cereja'
        | 'rubi'
        | 'purpura'
        | 'granada'
        | 'tawny'
      )
    | null;
  /**
   * Preenchido pela importação. Serve para apontar a canônica do beehiiv de volta para cá.
   */
  urlBeehiiv?: string | null;
  importadaEm?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * A agenda de vinho. Eventos passados somem da listagem sozinhos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos".
 */
export interface Evento {
  id: number;
  nome: string;
  /**
   * Preenchido sozinho a partir do título. Prefira slugs curtos, em português, com um tema só.
   */
  slug?: string | null;
  data: string;
  dataFim?: string | null;
  local?: string | null;
  cidade?: string | null;
  estado?: string | null;
  endereco?: string | null;
  tipo: 'degustacao' | 'feira' | 'jantar' | 'curso' | 'lancamento' | 'online';
  descricao: string;
  linkInscricao?: string | null;
  preco?: string | null;
  organizador?: string | null;
  destaque?: {
    imagem?: (number | null) | Midia;
    /**
     * Fotógrafo, ilustrador ou origem. Aparece embaixo da imagem.
     */
    credito?: string | null;
    legenda?: string | null;
  };
  /**
   * A faixa da escala cromática do vinho que representa este conteúdo. É o que dá cor ao cartão, à fita do boletim e aos filtros.
   */
  chipCor?:
    | (
        | 'verde-palha'
        | 'palha'
        | 'ouro'
        | 'ouro-velho'
        | 'ambar'
        | 'laranja'
        | 'rosa-palido'
        | 'salmao'
        | 'cobre'
        | 'cereja'
        | 'rubi'
        | 'purpura'
        | 'granada'
        | 'tawny'
      )
    | null;
  /**
   * Opcional. Se ficar em branco, usamos o título, o resumo e a imagem de destaque da própria página.
   */
  seo?: {
    /**
     * Até 70 caracteres. Aparece na aba do navegador e no resultado do Google.
     */
    titulo?: string | null;
    /**
     * Até 165 caracteres. É o parágrafo cinza embaixo do link no Google.
     */
    descricao?: string | null;
    /**
     * A imagem que aparece quando o link é colado no WhatsApp, Instagram ou X.
     */
    imagem?: (number | null) | Midia;
    /**
     * Separe por vírgula. Não vai para a meta keywords (que morreu) — serve de guia editorial e alimenta a busca interna.
     */
    palavrasChave?: string | null;
    /**
     * Use com muita parcimônia. O portal inteiro depende de ser encontrado.
     */
    naoIndexar?: boolean | null;
    /**
     * Só preencha se este conteúdo foi publicado antes em outro lugar e aquele endereço deve continuar sendo o oficial.
     */
    canonica?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Espelho local das inscrições. A lista oficial continua no beehiiv — isto é rede de segurança.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inscricoes".
 */
export interface Inscricao {
  id: number;
  email: string;
  nome?: string | null;
  /**
   * Qual página do site originou a inscrição.
   */
  origem?: string | null;
  statusBeehiiv?: ('sincronizada' | 'pendente' | 'falhou') | null;
  erroBeehiiv?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  nome: string;
  /**
   * Administrador mexe em tudo, inclusive em usuários. Editor escreve e publica conteúdo.
   */
  papel: 'administrador' | 'editor';
  /**
   * Liga este login à ficha pública de autoria, que aparece nas matérias.
   */
  autor?: (number | null) | Autor;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'usuarios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'materias';
        value: number | Materia;
      } | null)
    | ({
        relationTo: 'edicoes';
        value: number | Edicao;
      } | null)
    | ({
        relationTo: 'vinhos';
        value: number | Vinho;
      } | null)
    | ({
        relationTo: 'guias';
        value: number | Guia;
      } | null)
    | ({
        relationTo: 'eventos';
        value: number | Evento;
      } | null)
    | ({
        relationTo: 'autores';
        value: number | Autor;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'uvas';
        value: number | Uva;
      } | null)
    | ({
        relationTo: 'regioes';
        value: number | Regiao;
      } | null)
    | ({
        relationTo: 'importadoras';
        value: number | Importadora;
      } | null)
    | ({
        relationTo: 'midia';
        value: number | Midia;
      } | null)
    | ({
        relationTo: 'inscricoes';
        value: number | Inscricao;
      } | null)
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materias_select".
 */
export interface MateriasSelect<T extends boolean = true> {
  titulo?: T;
  subtitulo?: T;
  resumo?: T;
  destaque?:
    | T
    | {
        imagem?: T;
        credito?: T;
        legenda?: T;
      };
  corpo?: T;
  vinhosRelacionados?: T;
  materiasRelacionadas?: T;
  guiasRelacionados?: T;
  faq?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
        palavrasChave?: T;
        naoIndexar?: T;
        canonica?: T;
      };
  slug?: T;
  indiceBusca?: T;
  autor?: T;
  categoria?: T;
  tags?: T;
  chipCor?: T;
  dataPublicacao?: T;
  dataAtualizacao?: T;
  destaqueHome?: T;
  tempoLeitura?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "edicoes_select".
 */
export interface EdicoesSelect<T extends boolean = true> {
  titulo?: T;
  subtitulo?: T;
  resumo?: T;
  destaque?:
    | T
    | {
        imagem?: T;
        credito?: T;
        legenda?: T;
      };
  corpo?: T;
  blocos?:
    | T
    | {
        titulo?: T;
        ancora?: T;
        resumo?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
        palavrasChave?: T;
        naoIndexar?: T;
        canonica?: T;
      };
  numero?: T;
  slug?: T;
  indiceBusca?: T;
  dataEnvio?: T;
  dataPublicacao?: T;
  chipCor?: T;
  urlBeehiiv?: T;
  importadaEm?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vinhos_select".
 */
export interface VinhosSelect<T extends boolean = true> {
  nome?: T;
  produtor?: T;
  pais?: T;
  regiao?: T;
  subRegiao?: T;
  safra?: T;
  tipo?: T;
  corpo?: T;
  teorAlcoolico?: T;
  corNaEscala?: T;
  uvas?:
    | T
    | {
        uva?: T;
        percentual?: T;
        id?: T;
      };
  destaque?:
    | T
    | {
        imagem?: T;
        credito?: T;
        legenda?: T;
      };
  nota?: T;
  veredito?: T;
  notasDegustacao?: T;
  harmonizacoes?:
    | T
    | {
        prato?: T;
        observacao?: T;
        id?: T;
      };
  temperaturaServico?: T;
  potencialGuarda?: T;
  tacaRecomendada?: T;
  decantacao?: T;
  faixaPreco?: T;
  dataPreco?: T;
  importadora?: T;
  ondeComprar?:
    | T
    | {
        loja?: T;
        url?: T;
        afiliado?: T;
        id?: T;
      };
  materiasRelacionadas?: T;
  vinhosSimilares?: T;
  guiasRelacionados?: T;
  faq?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
        palavrasChave?: T;
        naoIndexar?: T;
        canonica?: T;
      };
  slug?: T;
  indiceBusca?: T;
  autor?: T;
  tags?: T;
  dataPublicacao?: T;
  dataAtualizacao?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guias_select".
 */
export interface GuiasSelect<T extends boolean = true> {
  titulo?: T;
  subtitulo?: T;
  resumo?: T;
  destaque?:
    | T
    | {
        imagem?: T;
        credito?: T;
        legenda?: T;
      };
  corpo?: T;
  paraLevar?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  conteudosRelacionados?: T;
  vinhosExemplo?: T;
  faq?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
        palavrasChave?: T;
        naoIndexar?: T;
        canonica?: T;
      };
  slug?: T;
  indiceBusca?: T;
  tipoGuia?: T;
  nivel?: T;
  autor?: T;
  tags?: T;
  chipCor?: T;
  dataPublicacao?: T;
  dataAtualizacao?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos_select".
 */
export interface EventosSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  data?: T;
  dataFim?: T;
  local?: T;
  cidade?: T;
  estado?: T;
  endereco?: T;
  tipo?: T;
  descricao?: T;
  linkInscricao?: T;
  preco?: T;
  organizador?: T;
  destaque?:
    | T
    | {
        imagem?: T;
        credito?: T;
        legenda?: T;
      };
  chipCor?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
        palavrasChave?: T;
        naoIndexar?: T;
        canonica?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autores_select".
 */
export interface AutoresSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  cargo?: T;
  bioCurta?: T;
  bioLonga?: T;
  foto?: T;
  credenciais?:
    | T
    | {
        texto?: T;
        ano?: T;
        link?: T;
        id?: T;
      };
  redes?:
    | T
    | {
        rede?: T;
        url?: T;
        id?: T;
      };
  email?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
        palavrasChave?: T;
        naoIndexar?: T;
        canonica?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  descricao?: T;
  chipCor?: T;
  ordem?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
        palavrasChave?: T;
        naoIndexar?: T;
        canonica?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uvas_select".
 */
export interface UvasSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  cor?: T;
  sinonimos?: T;
  descricao?: T;
  guia?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regioes_select".
 */
export interface RegioesSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  pais?: T;
  descricao?: T;
  guia?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "importadoras_select".
 */
export interface ImportadorasSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  site?: T;
  cidade?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "midia_select".
 */
export interface MidiaSelect<T extends boolean = true> {
  alt?: T;
  credito?: T;
  legenda?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        miniatura?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cartao?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        quadrado?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        retrato?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        largura?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        compartilhamento?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inscricoes_select".
 */
export interface InscricoesSelect<T extends boolean = true> {
  email?: T;
  nome?: T;
  origem?: T;
  statusBeehiiv?: T;
  erroBeehiiv?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nome?: T;
  papel?: T;
  autor?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Textos e ligações que aparecem em todas as páginas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes".
 */
export interface Configuracoes {
  id: number;
  nomeSite?: string | null;
  /**
   * A linha curta que acompanha o nome no cabeçalho e no rodapé.
   */
  assinatura?: string | null;
  /**
   * Usada como descrição padrão quando a página não tem uma própria.
   */
  descricao?: string | null;
  imagemPadrao?: (number | null) | Midia;
  /**
   * Quem assina a publicação. Alimenta a página /sobre e o schema.
   */
  autoraPrincipal?: (number | null) | Autor;
  boletimTitulo?: string | null;
  boletimChamada?: string | null;
  boletimPeriodicidade?: string | null;
  /**
   * A ordem aqui é a ordem no cabeçalho. Cinco itens já é bastante.
   */
  menu?:
    | {
        rotulo: string;
        endereco: string;
        id?: string | null;
      }[]
    | null;
  rodapeTexto?: string | null;
  redes?:
    | {
        rede: 'instagram' | 'youtube' | 'linkedin' | 'tiktok' | 'x';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * A frase de abertura da home. Deixe vazio para usar a descrição do site.
   */
  homeChamada?: string | null;
  /**
   * Opcional. Se ficar vazio, a home se monta sozinha com o conteúdo mais recente.
   */
  homeDestaques?:
    | (
        | {
            relationTo: 'materias';
            value: number | Materia;
          }
        | {
            relationTo: 'guias';
            value: number | Guia;
          }
        | {
            relationTo: 'vinhos';
            value: number | Vinho;
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes_select".
 */
export interface ConfiguracoesSelect<T extends boolean = true> {
  nomeSite?: T;
  assinatura?: T;
  descricao?: T;
  imagemPadrao?: T;
  autoraPrincipal?: T;
  boletimTitulo?: T;
  boletimChamada?: T;
  boletimPeriodicidade?: T;
  menu?:
    | T
    | {
        rotulo?: T;
        endereco?: T;
        id?: T;
      };
  rodapeTexto?: T;
  redes?:
    | T
    | {
        rede?: T;
        url?: T;
        id?: T;
      };
  homeChamada?: T;
  homeDestaques?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'materias';
          value: number | Materia;
        } | null)
      | ({
          relationTo: 'edicoes';
          value: number | Edicao;
        } | null)
      | ({
          relationTo: 'vinhos';
          value: number | Vinho;
        } | null)
      | ({
          relationTo: 'guias';
          value: number | Guia;
        } | null);
    global?: string | null;
    user?: (number | null) | Usuario;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}