/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    textos: Texto;
    vinhos: Vinho;
    midia: Midia;
    inscricoes: Inscricao;
    usuarios: Usuario;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    textos: TextosSelect<false> | TextosSelect<true>;
    vinhos: VinhosSelect<false> | VinhosSelect<true>;
    midia: MidiaSelect<false> | MidiaSelect<true>;
    inscricoes: InscricoesSelect<false> | InscricoesSelect<true>;
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    configuracoes: Configuracoes;
  };
  globalsSelect: {
    configuracoes: ConfiguracoesSelect<false> | ConfiguracoesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Tudo o que a Tanin publica.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textos".
 */
export interface Texto {
  id: number;
  titulo: string;
  subtitulo?: string | null;
  corpo: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  slug?: string | null;
  indiceBusca?: string | null;
  /**
   * De 40 a 60 palavras, escritas para fazer sentido sozinhas, fora da página. É o trecho que buscadores e IAs vão citar.
   */
  resumo?: string | null;
  capa?: (number | null) | Midia;
  palavrasChave?: string | null;
  tempoLeitura?: number | null;
  /**
   * A faixa da escala cromática do vinho que representa este conteúdo. É o que dá cor ao cartão, à fita do boletim e aos filtros.
   */
  chipCor?:
    | (
        | 'verde-palha'
        | 'palha'
        | 'ouro'
        | 'ouro-velho'
        | 'ambar'
        | 'laranja'
        | 'rosa-palido'
        | 'salmao'
        | 'cobre'
        | 'cereja'
        | 'rubi'
        | 'purpura'
        | 'granada'
        | 'tawny'
      )
    | null;
  /**
   * Deixe uma data futura para agendar. O conteúdo só aparece no site depois dela.
   */
  dataPublicacao?: string | null;
  /**
   * Aparece nas páginas evergreen. Atualize quando revisar o conteúdo.
   */
  dataAtualizacao?: string | null;
  secao: 'materia' | 'boletim' | 'guia';
  categoria?: ('reportagem' | 'ensaio' | 'entrevista' | 'degustacao' | 'mercado' | 'cultura') | null;
  tipoGuia?: ('uva' | 'regiao' | 'harmonizacao' | 'servico' | 'compra' | 'tecnico') | null;
  nivel?: ('iniciante' | 'intermediario') | null;
  numero?: number | null;
  paraLevar?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  destaque?: {
    imagem?: (number | null) | Midia;
    /**
     * Fotógrafo, ilustrador ou origem. Aparece embaixo da imagem.
     */
    credito?: string | null;
    legenda?: string | null;
  };
  /**
   * Cada par vira um bloco no fim da página e entra no código que o Google e as IAs leem. Responda de forma auto-contida, sem depender do resto do texto.
   */
  faq?:
    | {
        pergunta: string;
        resposta: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Se ficar em branco, usamos o título, o resumo e a imagem de destaque da própria página.
   */
  seo?: {
    /**
     * Até 70 caracteres. Aparece na aba do navegador e no resultado do Google.
     */
    titulo?: string | null;
    /**
     * Até 165 caracteres. É o parágrafo cinza embaixo do link no Google.
     */
    descricao?: string | null;
    /**
     * A imagem que aparece quando o link é colado no WhatsApp, Instagram ou X.
     */
    imagem?: (number | null) | Midia;
    /**
     * Separe por vírgula. Não vai para a meta keywords (que morreu) — serve de guia editorial e alimenta a busca interna.
     */
    palavrasChave?: string | null;
    /**
     * Use com muita parcimônia. O portal inteiro depende de ser encontrado.
     */
    naoIndexar?: boolean | null;
    /**
     * Só preencha se este conteúdo foi publicado antes em outro lugar e aquele endereço deve continuar sendo o oficial.
     */
    canonica?: string | null;
  };
  destaqueHome?: boolean | null;
  relacionados?:
    | (
        | {
            relationTo: 'textos';
            value: number | Texto;
          }
        | {
            relationTo: 'vinhos';
            value: number | Vinho;
          }
      )[]
    | null;
  urlBeehiiv?: string | null;
  importadaEm?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Imagens e ilustrações usadas no site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "midia".
 */
export interface Midia {
  id: number;
  /**
   * Descreve a imagem para quem não pode vê-la. Se ficar em branco, usamos a legenda.
   */
  alt?: string | null;
  /**
   * Fotógrafo, ilustrador ou banco de imagem.
   */
  credito?: string | null;
  /**
   * Usada quando a matéria não define uma legenda própria.
   */
  legenda?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    miniatura?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cartao?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    quadrado?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    retrato?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    largura?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    compartilhamento?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * As fichas. Cada uma é uma página que responde uma pergunta inteira sobre uma garrafa.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vinhos".
 */
export interface Vinho {
  id: number;
  nome: string;
  produtor?: string | null;
  pais?: string | null;
  regiao?: string | null;
  subRegiao?: string | null;
  /**
   * Deixe vazio para vinhos sem safra.
   */
  safra?: number | null;
  tipo: 'tinto' | 'branco' | 'rose' | 'espumante' | 'laranja' | 'fortificado';
  corpo?: ('leve' | 'medio' | 'encorpado') | null;
  teorAlcoolico?: number | null;
  /**
   * A cor real da taça. É o chip que a ficha carrega e o que liga a garrafa à escala cromática do portal.
   */
  corNaEscala:
    | 'verde-palha'
    | 'palha'
    | 'ouro'
    | 'ouro-velho'
    | 'ambar'
    | 'laranja'
    | 'rosa-palido'
    | 'salmao'
    | 'cobre'
    | 'cereja'
    | 'rubi'
    | 'purpura'
    | 'granada'
    | 'tawny';
  /**
   * Escreva o nome da uva. Deixe o percentual vazio quando o produtor não informa.
   */
  uvas?:
    | {
        uva: string;
        percentual?: number | null;
        id?: string | null;
      }[]
    | null;
  destaque?: {
    imagem?: (number | null) | Midia;
    /**
     * Fotógrafo, ilustrador ou origem. Aparece embaixo da imagem.
     */
    credito?: string | null;
    legenda?: string | null;
  };
  /**
   * Meias taças são permitidas: 3,5 · 4 · 4,5 · 5.
   */
  nota?: number | null;
  /**
   * Duas ou três frases que se sustentam sozinhas, fora da página. É o trecho que buscadores e IAs vão citar quando alguém perguntar sobre este vinho.
   */
  veredito?: string | null;
  notasDegustacao?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  harmonizacoes?:
    | {
        prato: string;
        observacao?: string | null;
        id?: string | null;
      }[]
    | null;
  temperaturaServico?: string | null;
  potencialGuarda?: string | null;
  tacaRecomendada?: string | null;
  decantacao?: string | null;
  /**
   * Cada par vira um bloco no fim da página e entra no código que o Google e as IAs leem. Responda de forma auto-contida, sem depender do resto do texto.
   */
  faq?:
    | {
        pergunta: string;
        resposta: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Se ficar em branco, usamos o título, o resumo e a imagem de destaque da própria página.
   */
  seo?: {
    /**
     * Até 70 caracteres. Aparece na aba do navegador e no resultado do Google.
     */
    titulo?: string | null;
    /**
     * Até 165 caracteres. É o parágrafo cinza embaixo do link no Google.
     */
    descricao?: string | null;
    /**
     * A imagem que aparece quando o link é colado no WhatsApp, Instagram ou X.
     */
    imagem?: (number | null) | Midia;
    /**
     * Separe por vírgula. Não vai para a meta keywords (que morreu) — serve de guia editorial e alimenta a busca interna.
     */
    palavrasChave?: string | null;
    /**
     * Use com muita parcimônia. O portal inteiro depende de ser encontrado.
     */
    naoIndexar?: boolean | null;
    /**
     * Só preencha se este conteúdo foi publicado antes em outro lugar e aquele endereço deve continuar sendo o oficial.
     */
    canonica?: string | null;
  };
  faixaPreco?: ('ate-80' | '80-150' | '150-250' | '250-400' | '400-700' | 'acima-700') | null;
  /**
   * Aparece na ficha, para o leitor saber o quanto a faixa está fresca.
   */
  dataPreco?: string | null;
  importadora?: {
    nome?: string | null;
    url?: string | null;
  };
  /**
   * Links informativos, sem afiliação. Se algum dia houver afiliação, marque abaixo — a transparência é parte da credibilidade.
   */
  ondeComprar?:
    | {
        loja: string;
        url: string;
        afiliado?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Preenchido sozinho a partir do título. Prefira slugs curtos, em português, com um tema só.
   */
  slug?: string | null;
  indiceBusca?: string | null;
  /**
   * Vinhos parecidos e textos que citam esta garrafa.
   */
  relacionados?:
    | (
        | {
            relationTo: 'textos';
            value: number | Texto;
          }
        | {
            relationTo: 'vinhos';
            value: number | Vinho;
          }
      )[]
    | null;
  /**
   * Deixe uma data futura para agendar. O conteúdo só aparece no site depois dela.
   */
  dataPublicacao?: string | null;
  /**
   * Aparece nas páginas evergreen. Atualize quando revisar o conteúdo.
   */
  dataAtualizacao?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Espelho local das inscrições. A lista oficial continua no beehiiv — isto é rede de segurança.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inscricoes".
 */
export interface Inscricao {
  id: number;
  email: string;
  nome?: string | null;
  /**
   * Qual página do site originou a inscrição.
   */
  origem?: string | null;
  statusBeehiiv?: ('sincronizada' | 'pendente' | 'falhou') | null;
  erroBeehiiv?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quem pode entrar no painel. Não confunda com a ficha pública da autora, que mora em Configurações.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  nome: string;
  /**
   * Administrador mexe em tudo, inclusive em usuários. Editor escreve e publica conteúdo.
   */
  papel: 'administrador' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'usuarios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'textos';
        value: number | Texto;
      } | null)
    | ({
        relationTo: 'vinhos';
        value: number | Vinho;
      } | null)
    | ({
        relationTo: 'midia';
        value: number | Midia;
      } | null)
    | ({
        relationTo: 'inscricoes';
        value: number | Inscricao;
      } | null)
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textos_select".
 */
export interface TextosSelect<T extends boolean = true> {
  titulo?: T;
  subtitulo?: T;
  corpo?: T;
  slug?: T;
  indiceBusca?: T;
  resumo?: T;
  capa?: T;
  palavrasChave?: T;
  tempoLeitura?: T;
  chipCor?: T;
  dataPublicacao?: T;
  dataAtualizacao?: T;
  secao?: T;
  categoria?: T;
  tipoGuia?: T;
  nivel?: T;
  numero?: T;
  paraLevar?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  destaque?:
    | T
    | {
        imagem?: T;
        credito?: T;
        legenda?: T;
      };
  faq?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
        palavrasChave?: T;
        naoIndexar?: T;
        canonica?: T;
      };
  destaqueHome?: T;
  relacionados?: T;
  urlBeehiiv?: T;
  importadaEm?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vinhos_select".
 */
export interface VinhosSelect<T extends boolean = true> {
  nome?: T;
  produtor?: T;
  pais?: T;
  regiao?: T;
  subRegiao?: T;
  safra?: T;
  tipo?: T;
  corpo?: T;
  teorAlcoolico?: T;
  corNaEscala?: T;
  uvas?:
    | T
    | {
        uva?: T;
        percentual?: T;
        id?: T;
      };
  destaque?:
    | T
    | {
        imagem?: T;
        credito?: T;
        legenda?: T;
      };
  nota?: T;
  veredito?: T;
  notasDegustacao?: T;
  harmonizacoes?:
    | T
    | {
        prato?: T;
        observacao?: T;
        id?: T;
      };
  temperaturaServico?: T;
  potencialGuarda?: T;
  tacaRecomendada?: T;
  decantacao?: T;
  faq?:
    | T
    | {
        pergunta?: T;
        resposta?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        imagem?: T;
        palavrasChave?: T;
        naoIndexar?: T;
        canonica?: T;
      };
  faixaPreco?: T;
  dataPreco?: T;
  importadora?:
    | T
    | {
        nome?: T;
        url?: T;
      };
  ondeComprar?:
    | T
    | {
        loja?: T;
        url?: T;
        afiliado?: T;
        id?: T;
      };
  slug?: T;
  indiceBusca?: T;
  relacionados?: T;
  dataPublicacao?: T;
  dataAtualizacao?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "midia_select".
 */
export interface MidiaSelect<T extends boolean = true> {
  alt?: T;
  credito?: T;
  legenda?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        miniatura?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cartao?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        quadrado?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        retrato?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        largura?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        compartilhamento?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inscricoes_select".
 */
export interface InscricoesSelect<T extends boolean = true> {
  email?: T;
  nome?: T;
  origem?: T;
  statusBeehiiv?: T;
  erroBeehiiv?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nome?: T;
  papel?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Textos e ligações que aparecem em todas as páginas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes".
 */
export interface Configuracoes {
  id: number;
  nomeSite?: string | null;
  /**
   * A linha curta que acompanha o nome no cabeçalho e no rodapé.
   */
  assinatura?: string | null;
  /**
   * Usada como descrição padrão quando a página não tem uma própria.
   */
  descricao?: string | null;
  imagemPadrao?: (number | null) | Midia;
  /**
   * A ficha pública da autora. Alimenta a página /sobre, o pé das matérias e o schema Person que buscadores e IAs leem.
   */
  autora?: {
    nome?: string | null;
    /**
     * Ex.: "Jornalista de vinho e criadora da Tanin".
     */
    cargo?: string | null;
    foto?: (number | null) | Midia;
    /**
     * Uma ou duas frases. Aparece no pé das matérias.
     */
    bioCurta?: string | null;
    /**
     * Texto completo da página /sobre.
     */
    bioLonga?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Formação, certificações, prêmios e veículos onde publicou. É o que sustenta a autoridade do portal aos olhos do Google e das IAs.
     */
    credenciais?:
      | {
          texto: string;
          ano?: string | null;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Entram no `sameAs` do schema — é assim que buscadores ligam a pessoa aos perfis dela.
     */
    redes?:
      | {
          rede: 'instagram' | 'linkedin' | 'youtube' | 'x' | 'tiktok' | 'site' | 'outro';
          url: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Opcional. Aparece na página /sobre se preenchido.
     */
    email?: string | null;
  };
  boletimTitulo?: string | null;
  boletimChamada?: string | null;
  boletimPeriodicidade?: string | null;
  /**
   * A ordem aqui é a ordem no cabeçalho. Cinco itens já é bastante.
   */
  menu?:
    | {
        rotulo: string;
        endereco: string;
        id?: string | null;
      }[]
    | null;
  rodapeTexto?: string | null;
  redes?:
    | {
        rede: 'instagram' | 'youtube' | 'linkedin' | 'tiktok' | 'x';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * A frase de abertura da home. Deixe vazio para usar a descrição do site.
   */
  homeChamada?: string | null;
  /**
   * Opcional. Se ficar vazio, a home se monta sozinha com o conteúdo mais recente.
   */
  homeDestaques?:
    | (
        | {
            relationTo: 'textos';
            value: number | Texto;
          }
        | {
            relationTo: 'vinhos';
            value: number | Vinho;
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes_select".
 */
export interface ConfiguracoesSelect<T extends boolean = true> {
  nomeSite?: T;
  assinatura?: T;
  descricao?: T;
  imagemPadrao?: T;
  autora?:
    | T
    | {
        nome?: T;
        cargo?: T;
        foto?: T;
        bioCurta?: T;
        bioLonga?: T;
        credenciais?:
          | T
          | {
              texto?: T;
              ano?: T;
              link?: T;
              id?: T;
            };
        redes?:
          | T
          | {
              rede?: T;
              url?: T;
              id?: T;
            };
        email?: T;
      };
  boletimTitulo?: T;
  boletimChamada?: T;
  boletimPeriodicidade?: T;
  menu?:
    | T
    | {
        rotulo?: T;
        endereco?: T;
        id?: T;
      };
  rodapeTexto?: T;
  redes?:
    | T
    | {
        rede?: T;
        url?: T;
        id?: T;
      };
  homeChamada?: T;
  homeDestaques?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'textos';
          value: number | Texto;
        } | null)
      | ({
          relationTo: 'vinhos';
          value: number | Vinho;
        } | null);
    global?: string | null;
    user?: (number | null) | Usuario;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}